// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationsDemo;

namespace MigrationsDemo.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20181206100030_Range")]
    partial class Range
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MigrationsDemo.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Name")
                        .HasMaxLength(31);

                    b.Property<DateTime?>("Time");

                    b.HasKey("BlogId");

                    b.HasIndex("BlogId")
                        .IsUnique();

                    b.ToTable("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
